/**
 * OpenParser public HTTP API wire contracts (requests, jobs, pipelines, catalogs).
 */

export {
  ExtractionPipelineIdInputSchema,
  JobIdInputSchema,
  LEGACY_OCR_JOB_UUID_PATTERN,
  LEGACY_OCR_PIPELINE_ID_PREFIX,
  isOcrJobIdInput,
  isPreferredOcrJobId,
  migratedOcrJobIdFromUuid,
  normalizeOcrJobIdInput,
  normalizeOcrPipelineIdInput,
  type ExtractionPipelineIdInput,
  type JobIdInput,
} from '../id-compat';

export {
  CreateExtractionPipelineRequestSchema,
  DeleteExtractionPipelineResponseSchema,
  DeleteFileResponseSchema,
  EXTRACT_INLINE_CONFIG_KEYS,
  ExtractBatchItemSchema,
  ExtractBatchRequestSchema,
  ExtractRequestSchema,
  ExtractionJsonSchemaObjectSchema,
  ExtractionPipelineIdSchema,
  ExtractionPipelineListResponseSchema,
  ExtractionPipelineNameSchema,
  ExtractionPipelineSchema,
  ExtractionPipelineSlugSchema,
  OPENPARSER_COMPONENT_SCHEMAS,
  OPENPARSER_ROUTE_MANIFEST,
  OcrFileIdSchema,
  OcrModelSchema,
  OpenParserParseResultSchema,
  ParseBatchItemSchema,
  ParseBatchRequestSchema,
  ParseRequestSchema,
  PublicFileSchema,
  RepairAttemptsSchema,
  SUGGEST_SCHEMA_HINT_MAX_CHARS,
  SUGGEST_SCHEMA_PREVIEW_MAX_CHARS,
  SUGGEST_SCHEMA_PREVIEW_MAX_PAGES,
  SuggestSchemaHintSchema,
  SuggestSchemaPreviewMetaSchema,
  SuggestSchemaRequestSchema,
  SuggestSchemaResponseSchema,
  SuggestSchemaTerminalResultSchema,
  UpdateExtractionPipelineRequestSchema,
  getOpenParserRoute,
  refineExtractPipelineXor,
  type CreateExtractionPipelineRequest,
  type DeleteExtractionPipelineResponse,
  type DeleteFileResponse,
  type ExtractBatchItem,
  type ExtractBatchRequest,
  type ExtractInlineRequest,
  type ExtractPipelineRequest,
  type ExtractRequest,
  type ExtractionPipeline,
  type ExtractionPipelineId,
  type ExtractionPipelineListResponse,
  type ExtractionPipelineName,
  type ExtractionPipelineSlug,
  type OcrFileId,
  type OcrModel,
  type OpenParserComponentSchemaName,
  type OpenParserOperationId,
  type OpenParserParseResult,
  type OpenParserRoute,
  type ParseBatchItem,
  type ParseBatchRequest,
  type ParseRequest,
  type PublicFile,
  type SuggestSchemaHint,
  type SuggestSchemaPreviewMeta,
  type SuggestSchemaRequest,
  type SuggestSchemaResponse,
  type SuggestSchemaTerminalResult,
  type UpdateExtractionPipelineRequest,
} from '../contracts';

export {
  OCR_LLM_REASONING_EFFORTS,
  OcrLlmModelCatalogEntrySchema,
  OcrLlmModelPricingSchema,
  OcrLlmModelReasoningSchema,
  OcrLlmModelsListModeSchema,
  OcrLlmModelsQuerySchema,
  OcrLlmModelsResponseSchema,
  OcrLlmPublicPricingBasisSchema,
  OcrLlmReasoningEffortRequestSchema,
  OcrLlmReasoningEffortSchema,
  OcrLlmRecommendationTierSchema,
  type OcrLlmModelCatalogEntry,
  type OcrLlmModelPricing,
  type OcrLlmModelReasoning,
  type OcrLlmModelsListMode,
  type OcrLlmModelsQuery,
  type OcrLlmModelsResponse,
  type OcrLlmPublicPricingBasis,
  type OcrLlmReasoningEffort,
  type OcrLlmReasoningEffortRequest,
  type OcrLlmRecommendationTier,
} from '../llm-models';

export {
  LlmOptionsRequestSchema,
  LlmOptionsStoredSchema,
  OcrModelOptionCapabilitySchema,
  OcrOptionsEffectiveSchema,
  OcrOptionsRequestSchema,
  PADDLE_OCR_OPTION_DEFAULTS,
  PaddleOcrOptionsEffectiveSchema,
  PaddleOcrOptionsRequestSchema,
  applyPaddleOcrOptionDefaults,
  type LlmOptionsRequest,
  type LlmOptionsStored,
  type OcrModelOptionCapability,
  type OcrOptionsEffective,
  type OcrOptionsRequest,
  type PaddleOcrOptionsEffective,
  type PaddleOcrOptionsRequest,
} from '../model-options';

export {
  OCR_MODELS,
  OCR_MODEL_CATALOG,
  OcrModelAvailabilitySchema,
  OcrModelCatalogEntrySchema,
  OcrModelPricingSchema,
  OcrModelsResponseSchema,
  PADDLE_OCR_USD_PER_PAGE,
  getDefaultOcrModelId,
  getOcrModelUsdPerPage,
  requireOcrModelUsdPerPage,
  type OcrModelAvailability,
  type OcrModelCatalogEntry,
  type OcrModelId,
  type OcrModelPricing,
  type OcrModelsResponse,
} from '../ocr-models';

export {
  OPENPARSER_CURL_API_KEY_PLACEHOLDER,
  OPENPARSER_CURL_IDEMPOTENCY_KEY_EXPR,
  OPENPARSER_DEFAULT_OUTPUT_FORMAT,
  OPENPARSER_IDEMPOTENCY_KEY_GUIDANCE,
  buildExtractPipelineCurl,
  buildOpenParserMultipartCurl,
  buildParseCurl,
  canonicalParseRequestExample,
  serializeOpenParserMultipartRequest,
  shellSingleQuote,
  type CanonicalParseRequestExample,
  type OpenParserMultipartAdmissionPath,
} from '../request-examples';

export {
  EXTRACTION_ATTEMPT_KINDS,
  EXTRACTION_ATTEMPT_STATUSES,
  ExtractionAttemptKindSchema,
  ExtractionAttemptSchema,
  ExtractionAttemptStatusSchema,
  ExtractionTerminalResultSchema,
  ExtractionUsageTotalsSchema,
  LlmModelSchema,
  type ExtractionAttempt,
  type ExtractionAttemptKind,
  type ExtractionAttemptStatus,
  type ExtractionTerminalResult,
  type ExtractionUsageTotals,
  type LlmModel,
} from '../extraction';

export {
  EXTRACTION_CITATION_GRANULARITIES,
  EXTRACTION_GROUNDING_MODES,
  ExtractionCitationGranularitySchema,
  ExtractionCitationSchema,
  ExtractionGroundingFieldSchema,
  ExtractionGroundingModeSchema,
  ExtractionGroundingResultSchema,
  type ExtractionCitation,
  type ExtractionCitationGranularity,
  type ExtractionGroundingField,
  type ExtractionGroundingMode,
  type ExtractionGroundingResult,
} from '../grounding';

export {
  BatchChildPageSchema,
  BatchChildSummarySchema,
  BatchJobAcceptedSchema,
  BatchSummaryCountsSchema,
  ErrorBodySchema,
  ErrorResponseSchema,
  JobAcceptedSchema,
  JobFailureSchema,
  JobHistoryOperationSchema,
  JobIdSchema,
  JobListQuerySchema,
  JobListResponseSchema,
  JobOperationSchema,
  JobProgressSchema,
  JobSchema,
  JobStatusSchema,
  JobSummarySchema,
  OCR_JOB_HISTORY_OPERATIONS,
  OCR_JOB_ID_PATTERN,
  OCR_JOB_ID_PREFIX,
  OCR_JOB_LIST_DEFAULT_LIMIT,
  OCR_JOB_LIST_MAX_LIMIT,
  OCR_JOB_OPERATIONS,
  OCR_JOB_STATUSES,
  OCR_OPENAPI_RELATIVE_PATH,
  OCR_SYNC_STATUS_CODES,
  RelatedExtractionSummarySchema,
  type BatchChildPage,
  type BatchChildSummary,
  type BatchJobAccepted,
  type BatchSummaryCounts,
  type ErrorBody,
  type ErrorResponse,
  type Job,
  type JobAccepted,
  type JobFailure,
  type JobHistoryOperation,
  type JobId,
  type JobListQuery,
  type JobListResponse,
  type JobOperation,
  type JobProgress,
  type JobStatus,
  type JobSummary,
  type RelatedExtractionSummary,
} from '../jobs';
