// Generated by packages/openparser-service/scripts/generate-hosted-sdk-models.ts — do not edit.

/**
 * Hosted OCR model IDs currently offered by the OpenParser API.
 * The wire `ocr_model` field remains `string` so future models work without an SDK bump.
 */
export const HOSTED_OCR_MODEL_IDS = [
  'paddleocr-vl-1.6',
  'mistral-ocr-4',
  'mistral-ocr-3',
  'azure-di-layout',
  'azure-di-read',
  'google-docai-ocr',
  'aws-textract-detect',
  'aws-textract-layout',
  'aws-textract-tables-layout',
] as const;

/** Literal union of known hosted OCR model IDs. */
export type HostedOcrModelId = (typeof HOSTED_OCR_MODEL_IDS)[number];

/** Default hosted OCR model when callers omit an explicit choice in product UIs. */
export const DEFAULT_HOSTED_OCR_MODEL_ID = 'paddleocr-vl-1.6' as const satisfies HostedOcrModelId;

/**
 * Hosted `ocr_options` for `paddleocr-vl-1.6` (PaddleOCR-VL 1.6).
 *
 * Output: Markdown + boxes.
 */
export type PaddleocrVl16Options = {
  /**
   * Image block OCR.
   *
   * OCR text inside images.
   */
  image_block_ocr?: boolean;
  /**
   * Chart recognition.
   *
   * Turn charts into structured content.
   */
  chart_recognition?: boolean;
  /**
   * Merge layout blocks.
   *
   * Merge nearby boxes for reading order.
   */
  merge_layout_blocks?: boolean;
};

/**
 * Hosted `ocr_options` for `mistral-ocr-4` (Mistral OCR 4).
 *
 * Output: Markdown + boxes.
 */
export type MistralOcr4Options = {
  /**
   * Table format.
   *
   * How tables are serialized in markdown output.
   */
  table_format?: 'html' | 'markdown';
  /**
   * Extract header.
   *
   * Include detected page headers in output.
   */
  extract_header?: boolean;
  /**
   * Extract footer.
   *
   * Include detected page footers in output.
   */
  extract_footer?: boolean;
  /**
   * Include blocks.
   *
   * Return structured layout blocks with the parse.
   */
  include_blocks?: boolean;
  /**
   * Confidence scores.
   *
   * Attach OCR confidence at page or word level.
   */
  confidence_scores_granularity?: 'page' | 'word' | null;
};

/**
 * Hosted `ocr_options` for `mistral-ocr-3` (Mistral OCR 3).
 *
 * Output: Markdown.
 */
export type MistralOcr3Options = {
  /**
   * Table format.
   *
   * How tables are serialized in markdown output.
   */
  table_format?: 'html' | 'markdown';
  /**
   * Extract header.
   *
   * Include detected page headers in output.
   */
  extract_header?: boolean;
  /**
   * Extract footer.
   *
   * Include detected page footers in output.
   */
  extract_footer?: boolean;
  /**
   * Confidence scores.
   *
   * Attach OCR confidence at page or word level.
   */
  confidence_scores_granularity?: 'page' | 'word' | null;
};

/**
 * Hosted `ocr_options` for `azure-di-layout` (Azure Document Intelligence Layout).
 *
 * Output: Markdown + boxes.
 */
export type AzureDiLayoutOptions = {
  /**
   * High-resolution OCR.
   *
   * Run OCR at higher resolution for small text.
   */
  high_resolution_ocr?: boolean;
  /**
   * Formulas.
   *
   * Detect and extract mathematical formulas.
   */
  formulas?: boolean;
  /**
   * Font styles.
   *
   * Capture font style metadata where available.
   */
  font_styles?: boolean;
  /**
   * Barcodes.
   *
   * Detect and decode barcodes.
   */
  barcodes?: boolean;
  /**
   * Languages.
   *
   * Detect document languages.
   */
  languages?: boolean;
  /**
   * Key-value pairs.
   *
   * Extract form-style key-value pairs.
   */
  key_value_pairs?: boolean;
  /**
   * Locale.
   *
   * BCP-47 locale hint (e.g. en-US). Leave empty for auto.
   */
  locale?: string | null;
  /**
   * Pages.
   *
   * Limit to page ranges (e.g. 1, 3-5). Leave empty for all pages.
   */
  pages?: string | null;
};

/**
 * Hosted `ocr_options` for `azure-di-read` (Azure Document Intelligence Read).
 *
 * Output: Plain text + boxes.
 */
export type AzureDiReadOptions = {
  /**
   * High-resolution OCR.
   *
   * Run OCR at higher resolution for small text.
   */
  high_resolution_ocr?: boolean;
  /**
   * Formulas.
   *
   * Detect and extract mathematical formulas.
   */
  formulas?: boolean;
  /**
   * Font styles.
   *
   * Capture font style metadata where available.
   */
  font_styles?: boolean;
  /**
   * Barcodes.
   *
   * Detect and decode barcodes.
   */
  barcodes?: boolean;
  /**
   * Languages.
   *
   * Detect document languages.
   */
  languages?: boolean;
  /**
   * Locale.
   *
   * BCP-47 locale hint (e.g. en-US). Leave empty for auto.
   */
  locale?: string | null;
  /**
   * Pages.
   *
   * Limit to page ranges (e.g. 1, 3-5). Leave empty for all pages.
   */
  pages?: string | null;
};

/**
 * Hosted `ocr_options` for `google-docai-ocr` (Google Enterprise Document OCR).
 *
 * Output: Markdown + boxes.
 */
export type GoogleDocaiOcrOptions = {
  /**
   * Native PDF parsing.
   *
   * Use embedded PDF text when available.
   */
  native_pdf_parsing?: boolean;
  /**
   * Image quality scores.
   *
   * Include image quality scores in the response.
   */
  image_quality_scores?: boolean;
  /**
   * Symbols.
   *
   * Return symbol-level OCR detail.
   */
  symbols?: boolean;
  /**
   * Language hints.
   *
   * Comma-separated BCP-47 codes (e.g. en, es). Leave empty for auto.
   */
  language_hints?: readonly string[] | null;
  /**
   * Math OCR.
   *
   * Enable math formula recognition.
   */
  math_ocr?: boolean;
  /**
   * Selection marks.
   *
   * Detect checkboxes and radio buttons.
   */
  selection_marks?: boolean;
  /**
   * Style info.
   *
   * Include text style metadata.
   */
  style_info?: boolean;
};

/**
 * Hosted `ocr_options` for `aws-textract-detect` (AWS Textract Detect).
 *
 * Output: Plain text + boxes.
 */
export type AwsTextractDetectOptions = {
  /**
   * Forms.
   *
   * Extract form fields as key-value pairs.
   */
  forms?: boolean;
  /**
   * Signatures.
   *
   * Detect handwritten and electronic signatures.
   */
  signatures?: boolean;
  /**
   * Queries.
   *
   * Comma-separated English questions to answer from every page (up to 30).
   */
  queries?: readonly string[] | null;
};

/**
 * Hosted `ocr_options` for `aws-textract-layout` (AWS Textract Layout).
 *
 * Output: Markdown + boxes.
 */
export type AwsTextractLayoutOptions = {
  /**
   * Forms.
   *
   * Extract form fields as key-value pairs.
   */
  forms?: boolean;
  /**
   * Signatures.
   *
   * Detect handwritten and electronic signatures.
   */
  signatures?: boolean;
  /**
   * Queries.
   *
   * Comma-separated English questions to answer from every page (up to 30).
   */
  queries?: readonly string[] | null;
};

/**
 * Hosted `ocr_options` for `aws-textract-tables-layout` (AWS Textract Tables + Layout).
 *
 * Output: Markdown + tables + boxes.
 */
export type AwsTextractTablesLayoutOptions = {
  /**
   * Forms.
   *
   * Extract form fields as key-value pairs.
   */
  forms?: boolean;
  /**
   * Signatures.
   *
   * Detect handwritten and electronic signatures.
   */
  signatures?: boolean;
  /**
   * Queries.
   *
   * Comma-separated English questions to answer from every page (up to 30).
   */
  queries?: readonly string[] | null;
};

/** Exact per-model hosted option types keyed by model id. */
export type HostedOcrOptionsByModel = {
  'paddleocr-vl-1.6': PaddleocrVl16Options;
  'mistral-ocr-4': MistralOcr4Options;
  'mistral-ocr-3': MistralOcr3Options;
  'azure-di-layout': AzureDiLayoutOptions;
  'azure-di-read': AzureDiReadOptions;
  'google-docai-ocr': GoogleDocaiOcrOptions;
  'aws-textract-detect': AwsTextractDetectOptions;
  'aws-textract-layout': AwsTextractLayoutOptions;
  'aws-textract-tables-layout': AwsTextractTablesLayoutOptions;
};

/**
 * Options type for a hosted model id.
 * Unknown/future string models fall back to an open record (escape hatch).
 */
export type HostedOcrOptionsFor<M extends string> = M extends HostedOcrModelId
  ? HostedOcrOptionsByModel[M]
  : Record<string, unknown>;

export type HostedParseRequestFields = {
  file_id?: string;
  output_format?: 'openparser@1' | 'raw';
};

/**
 * Typed parse request for a known or open `ocr_model` string.
 * Selecting a known hosted model checks `ocr_options` against that model's keys.
 */
export type HostedParseRequest<M extends string = string> = HostedParseRequestFields & {
  ocr_model: M;
  ocr_options?: HostedOcrOptionsFor<M>;
};

/**
 * Identity helper that preserves model-specific option checking at the call site.
 * Pass the result to `client.parse.sync` / `async` (existing generated wire API).
 */
export function hostedParseRequest<const M extends string>(
  request: HostedParseRequest<M>
): HostedParseRequest<M> {
  return request;
}

/**
 * Public catalog summaries for known hosted models.
 * No provider costs, private routes, markup, or guidance internals.
 */
export const HOSTED_OCR_MODEL_CATALOG_SUMMARY = {
  /**
   * PaddleOCR-VL 1.6.
   *
   * Output summary: Markdown + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'paddleocr-vl-1.6': {
    id: 'paddleocr-vl-1.6',
    label: 'PaddleOCR-VL 1.6',
    isDefault: true,
    outputSummary: 'Markdown + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: true,
      options: {
        image_block_ocr: true,
        chart_recognition: true,
        merge_layout_blocks: true,
      },
    },
    converter: {
      elementKinds: ['text', 'table', 'figure', 'formula', 'stamp'] as const,
      geometry: 'optional' as const,
      assets: 'optional' as const,
      textAnnotations: 'none' as const,
    },
  },
  /**
   * Mistral OCR 4.
   *
   * Output summary: Markdown + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'mistral-ocr-4': {
    id: 'mistral-ocr-4',
    label: 'Mistral OCR 4',
    isDefault: false,
    outputSummary: 'Markdown + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: true,
      options: {
        table_format: true,
        extract_header: true,
        extract_footer: true,
        include_blocks: true,
        confidence_scores_granularity: true,
      },
    },
    converter: {
      elementKinds: ['text', 'table', 'figure', 'signature', 'link'] as const,
      geometry: 'optional' as const,
      assets: 'optional' as const,
      textAnnotations: 'optional' as const,
    },
  },
  /**
   * Mistral OCR 3.
   *
   * Output summary: Markdown.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=false.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'mistral-ocr-3': {
    id: 'mistral-ocr-3',
    label: 'Mistral OCR 3',
    isDefault: false,
    outputSummary: 'Markdown',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: false,
      options: {
        table_format: true,
        extract_header: true,
        extract_footer: true,
        confidence_scores_granularity: true,
      },
    },
    converter: {
      elementKinds: ['text', 'table', 'figure', 'signature', 'link'] as const,
      geometry: 'optional' as const,
      assets: 'optional' as const,
      textAnnotations: 'optional' as const,
    },
  },
  /**
   * Azure Document Intelligence Layout.
   *
   * Output summary: Markdown + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'azure-di-layout': {
    id: 'azure-di-layout',
    label: 'Azure Document Intelligence Layout',
    isDefault: false,
    outputSummary: 'Markdown + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: true,
      options: {
        high_resolution_ocr: true,
        formulas: true,
        font_styles: true,
        barcodes: true,
        languages: true,
        key_value_pairs: true,
        locale: true,
        pages: true,
      },
    },
    converter: {
      elementKinds: [
        'text',
        'table',
        'key_value',
        'figure',
        'section',
        'formula',
        'barcode',
        'selection_mark',
      ] as const,
      geometry: 'optional' as const,
      assets: 'optional' as const,
      textAnnotations: 'optional' as const,
    },
  },
  /**
   * Azure Document Intelligence Read.
   *
   * Output summary: Plain text + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=false, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'azure-di-read': {
    id: 'azure-di-read',
    label: 'Azure Document Intelligence Read',
    isDefault: false,
    outputSummary: 'Plain text + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: false,
      regions: true,
      options: {
        high_resolution_ocr: true,
        formulas: true,
        font_styles: true,
        barcodes: true,
        languages: true,
        locale: true,
        pages: true,
      },
    },
    converter: {
      elementKinds: ['text', 'formula', 'barcode'] as const,
      geometry: 'optional' as const,
      assets: 'none' as const,
      textAnnotations: 'optional' as const,
    },
  },
  /**
   * Google Enterprise Document OCR.
   *
   * Output summary: Markdown + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'google-docai-ocr': {
    id: 'google-docai-ocr',
    label: 'Google Enterprise Document OCR',
    isDefault: false,
    outputSummary: 'Markdown + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: true,
      options: {
        native_pdf_parsing: true,
        image_quality_scores: true,
        symbols: true,
        language_hints: true,
        math_ocr: true,
        selection_marks: true,
        style_info: true,
      },
    },
    converter: {
      elementKinds: ['text', 'table', 'formula', 'selection_mark', 'other'] as const,
      geometry: 'optional' as const,
      assets: 'optional' as const,
      textAnnotations: 'optional' as const,
    },
  },
  /**
   * AWS Textract Detect.
   *
   * Output summary: Plain text + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=false, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'aws-textract-detect': {
    id: 'aws-textract-detect',
    label: 'AWS Textract Detect',
    isDefault: false,
    outputSummary: 'Plain text + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: false,
      regions: true,
      options: {
        forms: true,
        signatures: true,
        queries: true,
      },
    },
    converter: {
      elementKinds: ['text'] as const,
      geometry: 'optional' as const,
      assets: 'none' as const,
      textAnnotations: 'none' as const,
    },
  },
  /**
   * AWS Textract Layout.
   *
   * Output summary: Markdown + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'aws-textract-layout': {
    id: 'aws-textract-layout',
    label: 'AWS Textract Layout',
    isDefault: false,
    outputSummary: 'Markdown + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: true,
      options: {
        forms: true,
        signatures: true,
        queries: true,
      },
    },
    converter: {
      elementKinds: [
        'text',
        'table',
        'figure',
        'key_value',
        'query_answer',
        'signature',
        'selection_mark',
        'other',
      ] as const,
      geometry: 'optional' as const,
      assets: 'none' as const,
      textAnnotations: 'none' as const,
    },
  },
  /**
   * AWS Textract Tables + Layout.
   *
   * Output summary: Markdown + tables + boxes.
   * Capabilities: parse=true, extract_source=true, markdown=true, regions=true.
   * Converter elementKinds/geometry/assets describe a conservative upper bound — not guaranteed fields.
   */
  'aws-textract-tables-layout': {
    id: 'aws-textract-tables-layout',
    label: 'AWS Textract Tables + Layout',
    isDefault: false,
    outputSummary: 'Markdown + tables + boxes',
    capabilities: {
      parse: true,
      extract_source: true,
      markdown: true,
      regions: true,
      options: {
        forms: true,
        signatures: true,
        queries: true,
      },
    },
    converter: {
      elementKinds: [
        'text',
        'table',
        'figure',
        'key_value',
        'query_answer',
        'signature',
        'selection_mark',
        'other',
      ] as const,
      geometry: 'optional' as const,
      assets: 'none' as const,
      textAnnotations: 'none' as const,
    },
  },
} as const;

export type HostedOcrModelCatalogSummary = typeof HOSTED_OCR_MODEL_CATALOG_SUMMARY;
export type HostedOcrModelSummary<M extends HostedOcrModelId> = HostedOcrModelCatalogSummary[M];
