"""Generated by packages/openparser-service/scripts/generate-hosted-sdk-models.ts — do not edit.

Hosted OCR model syntactic sugar for the OpenParser Python SDK.

Public surface only: model IDs, option TypedDicts, capability/output summaries.
Does not include provider costs, private routes, markup, or guidance internals.
"""

from __future__ import annotations

from typing import Any, Literal, Mapping, Sequence, TypedDict, overload

from typing_extensions import NotRequired

HostedOcrModelId = Literal[
    "paddleocr-vl-1.6",
    "mistral-ocr-4",
    "mistral-ocr-3",
    "azure-di-layout",
    "azure-di-read",
    "google-docai-ocr",
    "aws-textract-detect",
    "aws-textract-layout",
    "aws-textract-tables-layout",
]

HOSTED_OCR_MODEL_IDS: tuple[HostedOcrModelId, ...] = (
    "paddleocr-vl-1.6",
    "mistral-ocr-4",
    "mistral-ocr-3",
    "azure-di-layout",
    "azure-di-read",
    "google-docai-ocr",
    "aws-textract-detect",
    "aws-textract-layout",
    "aws-textract-tables-layout",
)

DEFAULT_HOSTED_OCR_MODEL_ID: HostedOcrModelId = "paddleocr-vl-1.6"

class PaddleocrVl16Options(TypedDict):
    """Hosted ocr_options for paddleocr-vl-1.6 (PaddleOCR-VL 1.6).
    
    Output: Markdown + boxes.
    """
    # Image block OCR: OCR text inside images.
    image_block_ocr: NotRequired[bool]
    # Chart recognition: Turn charts into structured content.
    chart_recognition: NotRequired[bool]
    # Merge layout blocks: Merge nearby boxes for reading order.
    merge_layout_blocks: NotRequired[bool]

class MistralOcr4Options(TypedDict):
    """Hosted ocr_options for mistral-ocr-4 (Mistral OCR 4).
    
    Output: Markdown + boxes.
    """
    # Table format: How tables are serialized in markdown output.
    table_format: NotRequired[Literal["html", "markdown"]]
    # Extract header: Include detected page headers in output.
    extract_header: NotRequired[bool]
    # Extract footer: Include detected page footers in output.
    extract_footer: NotRequired[bool]
    # Include blocks: Return structured layout blocks with the parse.
    include_blocks: NotRequired[bool]
    # Confidence scores: Attach OCR confidence at page or word level.
    confidence_scores_granularity: NotRequired[Literal["page", "word"] | None]

class MistralOcr3Options(TypedDict):
    """Hosted ocr_options for mistral-ocr-3 (Mistral OCR 3).
    
    Output: Markdown.
    """
    # Table format: How tables are serialized in markdown output.
    table_format: NotRequired[Literal["html", "markdown"]]
    # Extract header: Include detected page headers in output.
    extract_header: NotRequired[bool]
    # Extract footer: Include detected page footers in output.
    extract_footer: NotRequired[bool]
    # Confidence scores: Attach OCR confidence at page or word level.
    confidence_scores_granularity: NotRequired[Literal["page", "word"] | None]

class AzureDiLayoutOptions(TypedDict):
    """Hosted ocr_options for azure-di-layout (Azure Document Intelligence Layout).
    
    Output: Markdown + boxes.
    """
    # High-resolution OCR: Run OCR at higher resolution for small text.
    high_resolution_ocr: NotRequired[bool]
    # Formulas: Detect and extract mathematical formulas.
    formulas: NotRequired[bool]
    # Font styles: Capture font style metadata where available.
    font_styles: NotRequired[bool]
    # Barcodes: Detect and decode barcodes.
    barcodes: NotRequired[bool]
    # Languages: Detect document languages.
    languages: NotRequired[bool]
    # Key-value pairs: Extract form-style key-value pairs.
    key_value_pairs: NotRequired[bool]
    # Locale: BCP-47 locale hint (e.g. en-US). Leave empty for auto.
    locale: NotRequired[str | None]
    # Pages: Limit to page ranges (e.g. 1, 3-5). Leave empty for all pages.
    pages: NotRequired[str | None]

class AzureDiReadOptions(TypedDict):
    """Hosted ocr_options for azure-di-read (Azure Document Intelligence Read).
    
    Output: Plain text + boxes.
    """
    # High-resolution OCR: Run OCR at higher resolution for small text.
    high_resolution_ocr: NotRequired[bool]
    # Formulas: Detect and extract mathematical formulas.
    formulas: NotRequired[bool]
    # Font styles: Capture font style metadata where available.
    font_styles: NotRequired[bool]
    # Barcodes: Detect and decode barcodes.
    barcodes: NotRequired[bool]
    # Languages: Detect document languages.
    languages: NotRequired[bool]
    # Locale: BCP-47 locale hint (e.g. en-US). Leave empty for auto.
    locale: NotRequired[str | None]
    # Pages: Limit to page ranges (e.g. 1, 3-5). Leave empty for all pages.
    pages: NotRequired[str | None]

class GoogleDocaiOcrOptions(TypedDict):
    """Hosted ocr_options for google-docai-ocr (Google Enterprise Document OCR).
    
    Output: Markdown + boxes.
    """
    # Native PDF parsing: Use embedded PDF text when available.
    native_pdf_parsing: NotRequired[bool]
    # Image quality scores: Include image quality scores in the response.
    image_quality_scores: NotRequired[bool]
    # Symbols: Return symbol-level OCR detail.
    symbols: NotRequired[bool]
    # Language hints: Comma-separated BCP-47 codes (e.g. en, es). Leave empty for auto.
    language_hints: NotRequired[Sequence[str] | None]
    # Math OCR: Enable math formula recognition.
    math_ocr: NotRequired[bool]
    # Selection marks: Detect checkboxes and radio buttons.
    selection_marks: NotRequired[bool]
    # Style info: Include text style metadata.
    style_info: NotRequired[bool]

class AwsTextractDetectOptions(TypedDict):
    """Hosted ocr_options for aws-textract-detect (AWS Textract Detect).
    
    Output: Plain text + boxes.
    """
    # Forms: Extract form fields as key-value pairs.
    forms: NotRequired[bool]
    # Signatures: Detect handwritten and electronic signatures.
    signatures: NotRequired[bool]
    # Queries: Comma-separated English questions to answer from every page (up to 30).
    queries: NotRequired[Sequence[str] | None]

class AwsTextractLayoutOptions(TypedDict):
    """Hosted ocr_options for aws-textract-layout (AWS Textract Layout).
    
    Output: Markdown + boxes.
    """
    # Forms: Extract form fields as key-value pairs.
    forms: NotRequired[bool]
    # Signatures: Detect handwritten and electronic signatures.
    signatures: NotRequired[bool]
    # Queries: Comma-separated English questions to answer from every page (up to 30).
    queries: NotRequired[Sequence[str] | None]

class AwsTextractTablesLayoutOptions(TypedDict):
    """Hosted ocr_options for aws-textract-tables-layout (AWS Textract Tables + Layout).
    
    Output: Markdown + tables + boxes.
    """
    # Forms: Extract form fields as key-value pairs.
    forms: NotRequired[bool]
    # Signatures: Detect handwritten and electronic signatures.
    signatures: NotRequired[bool]
    # Queries: Comma-separated English questions to answer from every page (up to 30).
    queries: NotRequired[Sequence[str] | None]

# Mapping used by type checkers / docs; values are TypedDict types, not instances.
HOSTED_OCR_OPTIONS_BY_MODEL: Mapping[HostedOcrModelId, type] = {
    "paddleocr-vl-1.6": PaddleocrVl16Options,
    "mistral-ocr-4": MistralOcr4Options,
    "mistral-ocr-3": MistralOcr3Options,
    "azure-di-layout": AzureDiLayoutOptions,
    "azure-di-read": AzureDiReadOptions,
    "google-docai-ocr": GoogleDocaiOcrOptions,
    "aws-textract-detect": AwsTextractDetectOptions,
    "aws-textract-layout": AwsTextractLayoutOptions,
    "aws-textract-tables-layout": AwsTextractTablesLayoutOptions,
}

HOSTED_OCR_MODEL_CATALOG_SUMMARY: dict[str, dict[str, Any]] = {
    "paddleocr-vl-1.6": {
        "id": "paddleocr-vl-1.6",
        "label": "PaddleOCR-VL 1.6",
        "is_default": True,
        "output_summary": "Markdown + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": True,
            "options": {
                "image_block_ocr": True,
                "chart_recognition": True,
                "merge_layout_blocks": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "figure", "formula", "stamp"),
            "geometry": "optional",
            "assets": "optional",
            "text_annotations": "none",
        },
    },
    "mistral-ocr-4": {
        "id": "mistral-ocr-4",
        "label": "Mistral OCR 4",
        "is_default": False,
        "output_summary": "Markdown + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": True,
            "options": {
                "table_format": True,
                "extract_header": True,
                "extract_footer": True,
                "include_blocks": True,
                "confidence_scores_granularity": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "figure", "signature", "link"),
            "geometry": "optional",
            "assets": "optional",
            "text_annotations": "optional",
        },
    },
    "mistral-ocr-3": {
        "id": "mistral-ocr-3",
        "label": "Mistral OCR 3",
        "is_default": False,
        "output_summary": "Markdown",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": False,
            "options": {
                "table_format": True,
                "extract_header": True,
                "extract_footer": True,
                "confidence_scores_granularity": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "figure", "signature", "link"),
            "geometry": "optional",
            "assets": "optional",
            "text_annotations": "optional",
        },
    },
    "azure-di-layout": {
        "id": "azure-di-layout",
        "label": "Azure Document Intelligence Layout",
        "is_default": False,
        "output_summary": "Markdown + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": True,
            "options": {
                "high_resolution_ocr": True,
                "formulas": True,
                "font_styles": True,
                "barcodes": True,
                "languages": True,
                "key_value_pairs": True,
                "locale": True,
                "pages": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "key_value", "figure", "section", "formula", "barcode", "selection_mark"),
            "geometry": "optional",
            "assets": "optional",
            "text_annotations": "optional",
        },
    },
    "azure-di-read": {
        "id": "azure-di-read",
        "label": "Azure Document Intelligence Read",
        "is_default": False,
        "output_summary": "Plain text + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": False,
            "regions": True,
            "options": {
                "high_resolution_ocr": True,
                "formulas": True,
                "font_styles": True,
                "barcodes": True,
                "languages": True,
                "locale": True,
                "pages": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "formula", "barcode"),
            "geometry": "optional",
            "assets": "none",
            "text_annotations": "optional",
        },
    },
    "google-docai-ocr": {
        "id": "google-docai-ocr",
        "label": "Google Enterprise Document OCR",
        "is_default": False,
        "output_summary": "Markdown + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": True,
            "options": {
                "native_pdf_parsing": True,
                "image_quality_scores": True,
                "symbols": True,
                "language_hints": True,
                "math_ocr": True,
                "selection_marks": True,
                "style_info": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "formula", "selection_mark", "other"),
            "geometry": "optional",
            "assets": "optional",
            "text_annotations": "optional",
        },
    },
    "aws-textract-detect": {
        "id": "aws-textract-detect",
        "label": "AWS Textract Detect",
        "is_default": False,
        "output_summary": "Plain text + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": False,
            "regions": True,
            "options": {
                "forms": True,
                "signatures": True,
                "queries": True,
            },
        },
        "converter": {
            "element_kinds": ("text",),
            "geometry": "optional",
            "assets": "none",
            "text_annotations": "none",
        },
    },
    "aws-textract-layout": {
        "id": "aws-textract-layout",
        "label": "AWS Textract Layout",
        "is_default": False,
        "output_summary": "Markdown + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": True,
            "options": {
                "forms": True,
                "signatures": True,
                "queries": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "figure", "key_value", "query_answer", "signature", "selection_mark", "other"),
            "geometry": "optional",
            "assets": "none",
            "text_annotations": "none",
        },
    },
    "aws-textract-tables-layout": {
        "id": "aws-textract-tables-layout",
        "label": "AWS Textract Tables + Layout",
        "is_default": False,
        "output_summary": "Markdown + tables + boxes",
        "capabilities": {
            "parse": True,
            "extract_source": True,
            "markdown": True,
            "regions": True,
            "options": {
                "forms": True,
                "signatures": True,
                "queries": True,
            },
        },
        "converter": {
            "element_kinds": ("text", "table", "figure", "key_value", "query_answer", "signature", "selection_mark", "other"),
            "geometry": "optional",
            "assets": "none",
            "text_annotations": "none",
        },
    },
}

@overload
def hosted_parse_request(
    ocr_model: Literal["paddleocr-vl-1.6"],
    /,
    *,
    ocr_options: PaddleocrVl16Options | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["mistral-ocr-4"],
    /,
    *,
    ocr_options: MistralOcr4Options | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["mistral-ocr-3"],
    /,
    *,
    ocr_options: MistralOcr3Options | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["azure-di-layout"],
    /,
    *,
    ocr_options: AzureDiLayoutOptions | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["azure-di-read"],
    /,
    *,
    ocr_options: AzureDiReadOptions | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["google-docai-ocr"],
    /,
    *,
    ocr_options: GoogleDocaiOcrOptions | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["aws-textract-detect"],
    /,
    *,
    ocr_options: AwsTextractDetectOptions | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["aws-textract-layout"],
    /,
    *,
    ocr_options: AwsTextractLayoutOptions | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: Literal["aws-textract-tables-layout"],
    /,
    *,
    ocr_options: AwsTextractTablesLayoutOptions | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...

@overload
def hosted_parse_request(
    ocr_model: str,
    /,
    *,
    ocr_options: Mapping[str, Any] | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]: ...


def hosted_parse_request(
    ocr_model: str,
    /,
    *,
    ocr_options: Mapping[str, Any] | None = None,
    file_id: str | None = None,
    output_format: Literal["openparser@1", "raw"] | None = None,
) -> dict[str, Any]:
    """Build a parse request dict with optional model-specific typing.

    Known hosted model IDs get per-model TypedDict checking via overloads.
    Arbitrary future model strings keep an open Mapping escape hatch and still
    produce a plain request dict for `OpenParserClient.parse.sync/async`.
    """
    request: dict[str, Any] = {"ocr_model": ocr_model}
    if ocr_options is not None:
        request["ocr_options"] = dict(ocr_options)
    if file_id is not None:
        request["file_id"] = file_id
    if output_format is not None:
        request["output_format"] = output_format
    return request


__all__ = [
    "HostedOcrModelId",
    "HOSTED_OCR_MODEL_IDS",
    "DEFAULT_HOSTED_OCR_MODEL_ID",
    "PaddleocrVl16Options",
    "MistralOcr4Options",
    "MistralOcr3Options",
    "AzureDiLayoutOptions",
    "AzureDiReadOptions",
    "GoogleDocaiOcrOptions",
    "AwsTextractDetectOptions",
    "AwsTextractLayoutOptions",
    "AwsTextractTablesLayoutOptions",
    "HOSTED_OCR_OPTIONS_BY_MODEL",
    "HOSTED_OCR_MODEL_CATALOG_SUMMARY",
    "hosted_parse_request",
]
