/**
 * Root entry — prefer subpath imports such as `@openparser/adapters/paddle`.
 */
export {
  OPENPARSER_ADAPTERS_VERSION,
  OPENPARSER_ADAPTER_KEYS,
  openparserAdapterConverterVersion,
  type OpenParserAdapterKey,
} from './adapters-version';

export {
  PADDLE_LAYOUT_OUTPUT_CAPABILITIES,
  PaddleAdapterError,
  assertPublicFigureUri,
  canonicalizeMarkdownFigureUris,
  mapLayoutResultsToParsedDocument,
  readDataInfoPages,
  resolveFigureBlockUri,
  rewriteMarkdownFigureUris,
  type FigureAssetUriMap,
  type FigureAssetsMode,
  type FigureUriValidator,
  type MapLayoutResultsInput,
  type PaddleLayoutParsedDocument,
  type PaddleLayoutPossibleElementKind,
  type PageDims,
} from './paddle/index';

export {
  MISTRAL_OCR_DEFAULT_BASE_URL,
  MISTRAL_OCR_DEFAULT_TIMEOUT_MS,
  MISTRAL_OCR_MAX_RESPONSE_BYTES,
  MISTRAL_OCR_OUTPUT_CAPABILITIES,
  MistralAdapterError,
  MistralOcr4RequestOptionsSchema,
  MistralOcrError,
  MistralOcrLegacyRequestOptionsSchema,
  MistralOcrRequestOptionsSchema,
  createHttpMistralOcrClient,
  mapMistralOcrResponseToParsedDocument,
  mistralModelSupportsIncludeBlocks,
  mistralOcrOptionsSchemaForModel,
  parseMistralOcrRequestOptions,
  toMistralOcrNativeRequestBody,
  type HttpMistralOcrClientOptions,
  type MapMistralOcrResponseInput,
  type MistralOcrParsedDocument,
  type MistralOcrPossibleElementKind,
  type MistralOcrRequestOptions,
  type MistralParseInput,
  type MistralParseOutput,
} from './mistral/index';

export {
  AZURE_DI_API_VERSION,
  AZURE_DI_DEFAULT_POLL_INTERVAL_MS,
  AZURE_DI_DEFAULT_POLL_TIMEOUT_MS,
  AZURE_DI_DEFAULT_REQUEST_TIMEOUT_MS,
  AZURE_DI_FEATURE_PARAM_BY_OPTION,
  AZURE_DI_LAYOUT_OUTPUT_CAPABILITIES,
  AZURE_DI_MAX_RESPONSE_BYTES,
  AZURE_DI_MAX_RETRY_AFTER_MS,
  AZURE_DI_READ_OUTPUT_CAPABILITIES,
  AzureDiError,
  AzureDiLayoutParseOptionsSchema,
  AzureDiReadParseOptionsSchema,
  AzureDocumentIntelligenceAdapterError,
  AzureParseOptionsSchema,
  azureDiOptionsSchemaForModel,
  azureModelSupportsKeyValuePairs,
  createHttpAzureDiClient,
  mapAzureDocumentIntelligenceToParsedDocument,
  parseAzureDiParseOptions,
  resolveAzureDiAnalyzeParams,
  type AzureDiLayoutParsedDocument,
  type AzureDiReadParsedDocument,
  type AzureDocumentIntelligenceAnalyzeResult,
  type AzureParseInput,
  type AzureParseOptions,
  type AzureParseOutput,
  type HttpAzureDiClientOptions,
  type MapAzureDocumentIntelligenceInput,
  type ResolvedAzureDiAnalyzeParams,
} from './azure-document-intelligence/index';

export {
  GOOGLE_DOCAI_API_VERSION,
  GOOGLE_DOCAI_CLOUD_PLATFORM_SCOPE,
  GOOGLE_DOCAI_DEFAULT_TIMEOUT_MS,
  GOOGLE_DOCAI_MAX_ERROR_CHARS,
  GOOGLE_DOCAI_MAX_RESPONSE_BYTES,
  GOOGLE_DOCAI_OCR_OUTPUT_CAPABILITIES,
  GOOGLE_DOCAI_OCR_PROCESSOR_TYPE,
  GOOGLE_DOCAI_PROCESSOR_TYPE,
  GOOGLE_DOCAI_RASTER_OCR_TIMEOUT_MS,
  GOOGLE_DOCAI_SYNC_MAX_PDF_PAGES,
  GoogleDocumentAiAdapterError,
  GoogleDocumentAiError,
  GoogleDocumentAiOcrOptionsSchema,
  createGoogleDocumentAiClient,
  mapGoogleDocumentAiToParsedDocument,
  parseGoogleDocumentAiOcrOptions,
  toGoogleDocumentAiProcessOptions,
  type GoogleAuthHeaders,
  type GoogleDocAiOcrParsedDocument,
  type GoogleDocumentAiClient,
  type GoogleDocumentAiClientOptions,
  type GoogleDocumentAiOcrOptions,
  type GoogleDocumentAiParseInput,
  type GoogleDocumentAiParseOutput,
  type GoogleDocumentAiProcessorType,
  type GoogleDocumentAiResponse,
  type MapGoogleDocumentAiInput,
} from './google-document-ai/index';

export {
  AWS_TEXTRACT_ANALYZE_OUTPUT_CAPABILITIES,
  AWS_TEXTRACT_CLIENT_REQUEST_TOKEN_MAX,
  AWS_TEXTRACT_DEFAULT_POLL_INTERVAL_MS,
  AWS_TEXTRACT_DEFAULT_TIMEOUT_MS,
  AWS_TEXTRACT_DETECT_OUTPUT_CAPABILITIES,
  AWS_TEXTRACT_FEATURE_TYPES,
  AWS_TEXTRACT_MAX_ERROR_CHARS,
  AWS_TEXTRACT_MAX_POLL_INTERVAL_MS,
  AWS_TEXTRACT_MAX_RESULT_PAGES,
  AwsTextractAdapterError,
  AwsTextractAnalyzeOptionsSchema,
  AwsTextractError,
  AwsTextractFeatureTypeSchema,
  assertAwsTextractAnalyzeCompatibility,
  createAwsTextractClient,
  mapAwsTextractToParsedDocument,
  parseAwsTextractAnalyzeOptions,
  resolveAwsTextractFeatureTypes,
  textractClientRequestToken,
  type AwsTextractAnalyzeOptions,
  type AwsTextractAnalyzeParsedDocument,
  type AwsTextractClient,
  type AwsTextractClientOptions,
  type AwsTextractDetectParsedDocument,
  type AwsTextractFeatureType,
  type AwsTextractFeatureTypeName,
  type AwsTextractOperation,
  type AwsTextractParseInput,
  type AwsTextractParseOutput,
  type AwsTextractResponse,
  type AwsTextractSdkClient,
  type AwsTextractSourceObject,
  type MapAwsTextractInput,
} from './aws-textract/index';
